# Generated by Django 2.2.24 on 2021-12-22 07:39

import phonenumbers
from django.db import migrations


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            phone = phonenumbers.parse(
                flat.owners_phonenumber,
                'RU'
            )
        except phonenumbers.NumberParseException:
            continue
        else:
            if phonenumbers.is_valid_number(phone):
                flat.owner_pure_phone = phone
                flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20211222_1033'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone)
    ]
