# Generated by Django 2.2.24 on 2021-12-24 08:23

from django.db import migrations


def make_link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner_flats = Flat.objects.filter(
            owner=owner.full_name,
            owners_phonenumber=owner.phone
        )
        owner.flats.set(owner_flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20211224_1122'),
    ]

    operations = [
        migrations.RunPython(make_link_owners_to_flats)
    ]
